### ISSUE TITLE
Cant get it to work with SW=V14.0m5

### ISSUE THREAD

**Issue by zLucPlayZ** [TheRealKillaruna/nano_pk#2]
Hey,

I just got the nano pk installed.
Now im trying to get it to work.

I tried to 2 presets, non of them worked, so I figured, I'll throw in a sd card, and set a custom message format. Still gettting errors, and it doesnt work.

My Configuration in HA:

```
nano_pk:
  host: 10.0.135.198
  msgformat: "<DAQPRJ>[TURNCATED; see attached DAQ output]</DAQPRJ>"
  devicename: Nano-PK
  parameters: STANDARD
  language: DE
  ```

[DAQ_output.txt](https://github.com/TheRealKillaruna/nano_pk/files/7143898/DAQ_output.txt)

The interface and the tcp socket is indeed reachable, and also prints out data upon connecting to the tcp socket.
Looks like this:

```
root@raspberrypi:~# telnet 10.0.135.198 23
Trying 10.0.135.198...
Connected to 10.0.135.198.
Escape character is '^]'.
pm 1 1.2 0 59.3 0 63.0 0 0 0 0 10 2 0 0 0 28.9 25.4 68.1 -20 67.0 -20 57.6 68 62.4 32 34 115.5 0 0 0 0 0 0 0 0 4 0 0 -3 51 0 0 99 30 16 0 0 12 1 0 -20 0 20 20 0 1 28.5 0 20 20 5 1 140 0 20 20 0 1 -20 0 20 20 0 1 -20 0 20 20 0 1 -20 0 20 20 0 1 -20 0 20 20 0 1 -20 0 0 52.0 0 0 -20 0 0 -20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 140 3 3 -20 0 0 24200 -20 0 0 -20 0 20 20 0 20 1 3 -100 5 0 0 9 0 0 0 0 100 0 0 
pm 1 1.2 0 59.3 0 63.1 0 0 0 0 11 2 0 0 0 28.9 25.4 68.1 -20 67.0 -20 57.6 68 62.4 32 34 115.5 0 0 0 0 0 0 0 0 4 0 0 -3 51 0 0 99 30 16 0 0 12 1 0 -20 0 20 20 0 1 28.5 0 20 20 5 1 140 0 20 20 0 1 -20 0 20 20 0 1 -20 0 20 20 0 1 -20 0 20 20 0 1 -20 0 20 20 0 1 -20 0 0 52.0 0 0 -20 0 0 -20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 140 3 3 -20 0 0 24201 -20 0 0 -20 0 20 20 0 20 1 3 -100 5 0 0 1 0 0 0 0 100 0 0 
pm 1 1.2 0 59.3 0 63.1 0 0 0 0 10 2 0 0 0 28.9 25.4 68.1 -20 67.0 -20 57.6 68 62.4 32 34 113.6 0 0 0 0 0 0 0 0 4 0 0 -3 51 0 0 99 30 16 0 0 12 1 0 -20 0 20 20 0 1 28.5 0 20 20 5 1 140 0 20 20 0 1 -20 0 20 20 0 1 -20 0 20 20 0 1 -20 0 20 20 0 1 -20 0 20 20 0 1 -20 0 0 52.0 0 0 -20 0 0 -20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 140 3 3 -20 0 0 24200 -20 0 0 -20 0 20 20 0 20 1 3 -100 5 0 0 1 0 0 0 0 100 0 0 
```

**Comment by zLucPlayZ** [comment]
Forgot, to add, that the error was: Received message has unexpected length.

This is true, after some research with the data, i noticed, that the lengths are indeed different. Expected are: 148, but got: 154.

Something seems off, as the expected should be 154 with my config.

**Comment by TheRealKillaruna** [comment]
@zLucPlayZ Thanks for posting the DAQ file! The issue was that there are duplicate DUMMY parameters that messed up the indexing and the expected message length. This is now fixed with the latest commit. I have also added the new firmware version as preset, you should be able to activate it with `msgformat: NANO_V14M` in your config file. Please let me know if it works...

**Comment by zLucPlayZ** [comment]
@TheRealKillaruna This works perfectly fine, thank you very much.
Also, what I noticed, in the script it says that the heater sends 2 messages a second, but I see like 1 message a second from mine.

But there is another issue Im currently experiencing and testing around. And I think I might found the cause.
The issue is: It just randomly stops working, no logs.
So I enabled debug for the integration, and saw, that no new parameters are being sent by the heater whenever this occurs. So it might be good, to add a counter, the keeps track of the empty messages in a row, and If this beyond a reasonable threshold, reopen the telnet connection?

**Comment by TheRealKillaruna** [comment]
@zLucPlayZ Interesting that you only receive 1 message per second, they might have changed the frequency with the latest firmware. Have you tried decreasing the update frequency to see if that helps with your telnet issues? In line 23 of sensor.py, you could add a longer delay between updated, e.g. `bridge = HargassnerBridge(host, updateInterval=3.0, msgFormat=format)` to wait 3 secs for new data instead of the standard 1 second.
However, I don't see anything in the code that could become problematic with the default (or even a higher) update frequency. Your idea with resetting the telnet connection if no data is received for a certain time is great! I will implement it if I find a bit of time and let you know here so you can test it.

**Comment by zLucPlayZ** [comment]
@TheRealKillaruna 1 second seem correct for me. I added a simple version of what I explained above, and that seems to fix my issues for now. I think the nano pk controller restarts, or whatever it does, but it becomes unavailable sometimes (not reachable over my network). And that fixes itself after a minute or two, when it reconnects after its available again, because of my temporary implementation.

Would highly appreciate a implementation for that :D
